mysite/food/urls.py
from django.urls import path

from . import views

app_name="food"
urlpatterns = [
    path('', views.index, name="index"),
    path('item/', views.item, name="item"),
    path('<int:item_id>/', views.detail, name="detail"),
    
    path('add', views.create_item, name='create_item'),
    path('update/<int:id>/', views.update_item, name='update_item'),
    path('delete/<int:id>/', views.delete_item, name='delete_item'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
]

mysite/food/models.py
from typing import Type
from django.db import models

# Create your models here.
class Item(models.Model):
    def __str__(self):
        return self.item_name
    
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_image = models.CharField(max_length=500 , default="https://www.shutterstock.com/image-vector/exciting-new-cafe-bar-restaurant-600nw-2145440019.jpg")
    item_price = models.IntegerField()

mysite/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

mysite/food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from .forms import ItemForm
from .models import Item
from django.template import context, loader
# Create your views here.
def index(request):
    item_list = Item.objects.all()
    # template = loader.get_template("food/index.html")
    context ={
        "item_list": item_list,
    }
    # return HttpResponse(template.render(context, request))
    return render(request, "food/index.html", context )

def item(request):
    return HttpResponse(f"<h1> welcome to food app see the item </h1>")

def detail(request, item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item':item,
    }
    return render(request, "food/detail.html", context)

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request, 'food/item-form.html', {'form': form })

def update_item(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request, 'food/item-form.html', {'form': form, 'item': item })

def delete_item(request, id):
    item = Item.objects.get(id=id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    return render(request, 'food/item-delete.html', {'item': item} )

mysite/food/templates/food/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base page</title>
    <link rel="stylesheet" href="{% static "food/style.css" %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Food</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'food:create_item'%}">Add Item</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>

      {% block body %}
      {% endblock %}

</body>
</html>

mysite/food/templates/food/detail.html
{% extends "food/base.html" %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img class="card" height="180px"  width="240px" src="{{item.item_image}}" alt="">
        </div>
        <div class="col-md-6">
            <h1>{{item.item_name}}</h1>
            <h2>{{item.item_desc}}</h2>
            <h3>${{item.item_price}}</h3>
           
            <a href="{% url 'food:update_item' item.id %}" class="btn btn-primary">Edit</a>

            <a href="{% url 'food:delete_item' item.id %}" class="btn btn-danger">Delete</a>


        </div>
    </div>
</div>

{% comment %} <h1>{{item.item_name}}</h1>
<h2>{{item.item_desc}}</h2>
<h2>{{item.item_price}}</h2> {% endcomment %}
{% comment %} <h2>{{item.item_image}}</h2> {% endcomment %}

{% endblock %}

mysite/food/templates/food/index.html
 {% extends "food/base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% comment %} <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> {% endcomment %}
    <title>Food app</title>
   

</head>
<body>

    {% block body %}
    {% for item in item_list %}
    <div class="row">
        <div class="col-md-3 offset-md-2  ">
            <img class="card m-4px" height="100px"  width="100px" src="{{ item.item_image }}" alt=""/>

        </div>
        <div class="col-md-4">
            <h2>{{ item.item_name }}</h2>
            <h2>{{ item.item_desc }}</h2>
            <h4>${{ item.item_price }}</h4>
           
        </div>
        <div class="col-md-2">
            <a href="{% url "food:detail" item.id %}" class="btn btn-success">Details</a>
        </div>
    </div>
    
    
    {% endfor %}
{% endblock %}


    {% comment %} <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Template for food items</title>
</head>
<body>
    <h1>Your Favourite Food Items are here </h1>
</body>
</html> {% endcomment %}


{% comment %} 
{% for item  in item_list %}
{% comment %} {{ item.id}}  -- {{ item.item_name }} -- {{item.item_desc}} {% endcomment %}

{% comment %} <ul> {% endcomment %}
   {% comment %} <a href="/food/{{item.id}}"><li>{{ item.id}}  -- {{ item.item_name }} </li></a>  {% endcomment %}
   {% comment %} <a href="{% url "food:detail" item.id %}"><li>{{ item.id}}  -- {{ item.item_name }} </li></a>  {% endcomment %}
{% comment %} </ul> {% endcomment %}


</body>
</html>

mysite/food/templates/food/item-delete.html
<form action="{% url 'food:delete_item' item.id %}" method="post">
{% csrf_token %}
<h2>Are you sure want to delete {{item.item_name}}</h2>
<button type="submit" class="btn btn-danger">Confirm</button> 

</form>

mysite/food/templates/food/item-form.html
{% extends "food/base.html" %}
{% block body %}
<form action="" method="post">

    {% csrf_token %}
        <button type="submit" class="btn btn-success">Save</button>
    {{form}}
</form>

{% endblock  %}